name: Test
on:
  push
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    container: perl:5.08
    steps:
    - uses: actions/checkout@v2
    - name: Install FLAT
      run: |
        cpanm install FLAT Test::More Test::Exception
    - name: Test
      run: |
        prove -lr ./t
    runs-on: ubuntu-latest
    container: perl:5.10
    steps:
    - uses: actions/checkout@v2
    - name: Install FLAT
      run: |
        cpanm install FLAT Test::More Test::Exception
    - name: Test
      run: |
        prove -lr ./t
