name: Test
on:
  push
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    container: perl:5.14
    steps:
    - uses: actions/checkout@v2
    - name: Install FLAT
      run: |
        cpanm install FLAT Test::More Test::Exception
    - name: Test
      run: |
        cpanm -n --with-recommends --installdeps .
        prove -lr ./t
